server {
    listen 80; # 监听HTTP端口
    server_name sandbox.zhangyiduo.top; # 域名

    location / {
        proxy_pass http://8.137.108.78:8106; # 将请求转发到Java应用程序
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
